const KEY='ems_v2';
const seed={employees:[
{id:'EMP101',name:'Vincent Odhiambo',email:'vincent@ems.local',phone:'+254700000001',dept:'Engineering',designation:'Software Developer',joined:'2025-01-15',salary:85000,status:'Active'},
{id:'EMP102',name:'Sarah Jenkins',email:'sarah@ems.local',phone:'+254700000002',dept:'Human Resources',designation:'HR Manager',joined:'2024-08-12',salary:105000,status:'Active'},
{id:'EMP103',name:'Michael Scott',email:'michael@ems.local',phone:'+254700000003',dept:'Sales',designation:'Sales Manager',joined:'2023-04-10',salary:98000,status:'Active'},
{id:'EMP104',name:'Emily Watson',email:'emily@ems.local',phone:'+254700000004',dept:'Engineering',designation:'UI/UX Designer',joined:'2025-05-20',salary:78000,status:'On Leave'},
{id:'EMP105',name:'Daniel Otieno',email:'daniel@ems.local',phone:'+254700000005',dept:'Finance',designation:'Accountant',joined:'2022-11-03',salary:92000,status:'Active'}
],departments:[
{id:'DEP1',name:'Engineering',manager:'Vincent Odhiambo',budget:4200000},{id:'DEP2',name:'Human Resources',manager:'Sarah Jenkins',budget:3000000},{id:'DEP3',name:'Sales',manager:'Michael Scott',budget:3600000},{id:'DEP4',name:'Finance',manager:'Daniel Otieno',budget:3200000}
],attendance:[],leaves:[
{id:'L1',emp:'Emily Watson',type:'Casual Leave',start:'2026-08-17',end:'2026-08-19',days:3,reason:'Personal work',status:'Approved'},
{id:'L2',emp:'Vincent Odhiambo',type:'Sick Leave',start:'2026-08-20',end:'2026-08-21',days:2,reason:'Medical appointment',status:'Pending'}
],reviews:[
{id:'R1',emp:'Sarah Jenkins',reviewer:'Vincent Odhiambo',rating:5,goal:'Expand HR team',feedback:'Excellent leadership and communication.'},
{id:'R2',emp:'Michael Scott',reviewer:'Sarah Jenkins',rating:4,goal:'Increase quarterly sales',feedback:'Strong results; improve pipeline forecasting.'}
],payroll:{},activities:[],notifications:[]};
let state=load();let user=null;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function toast(msg,type='success'){const x=document.createElement('div');x.className='toast '+type;x.textContent=msg;document.getElementById('toast').appendChild(x);setTimeout(()=>x.remove(),2800)}
function money(n){return 'KSh '+Number(n||0).toLocaleString('en-KE',{maximumFractionDigits:0})}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function today(){return new Date().toISOString().slice(0,10)}
function initials(n){return n.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function log(text){state.activities.unshift({text,time:new Date().toLocaleString()});state.activities=state.activities.slice(0,30);state.notifications.unshift({id:Date.now(),text,read:false,time:new Date().toLocaleString()});save()}
function roleAllowed(el){return (el.dataset.roles||'Admin,HR Manager,Employee').split(',').includes(user?.role)}
function setup(){
 document.getElementById('loginForm').onsubmit=login;document.getElementById('logoutBtn').onclick=logout;
 document.getElementById('themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('ems_theme',document.body.classList.contains('dark')?'dark':'light')};
 document.getElementById('menuBtn').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
 document.querySelectorAll('#nav button[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));document.querySelectorAll('[data-page-jump]').forEach(b=>b.onclick=()=>go(b.dataset.pageJump));
 ['empSearch','empDept','empStatus'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderEmployees));
 document.getElementById('addEmployee').onclick=()=>employeeModal();document.getElementById('addDepartment').onclick=()=>departmentModal();document.getElementById('applyLeave').onclick=()=>leaveModal();document.getElementById('addReview').onclick=()=>reviewModal();document.getElementById('clockBtn').onclick=clock;document.getElementById('processPayroll').onclick=processPayroll;
 document.getElementById('exportPayroll').onclick=()=>exportCSV('payroll.csv',payrollRows());document.getElementById('exportAttendance').onclick=()=>exportCSV('attendance.csv',attendanceRows());document.getElementById('exportReport').onclick=()=>exportCSV('ems-report.csv',reportRows());
 document.getElementById('markRead').onclick=()=>{state.notifications.forEach(n=>n.read=true);save();renderNotifications()};document.getElementById('closeModal').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
 if(localStorage.getItem('ems_theme')==='dark')document.body.classList.add('dark');setInterval(updateClock,1000);updateClock()
}
function login(e){e.preventDefault();const email=document.getElementById('loginEmail').value.trim();const role=document.getElementById('loginRole').value;user={name:email.split('@')[0].replace(/[._-]/g,' '),email,role};localStorage.setItem('ems_user',JSON.stringify(user));start()}
function start(){user=JSON.parse(localStorage.getItem('ems_user')||'null');if(!user)return;document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userName').textContent=user.name;document.getElementById('heroName').textContent=user.name.split(' ')[0];document.getElementById('userRole').textContent=user.role;document.getElementById('avatar').textContent=initials(user.name);document.querySelectorAll('#nav button[data-roles]').forEach(b=>b.style.display=roleAllowed(b)?'flex':'none');renderAll();go('dashboard')}
function logout(){localStorage.removeItem('ems_user');user=null;document.getElementById('app').classList.add('hidden');document.getElementById('login').classList.remove('hidden')}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-'+page)?.classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===page));document.getElementById('pageTitle').textContent=page[0].toUpperCase()+page.slice(1);document.querySelector('.sidebar').classList.remove('open');renderAll()}
function renderAll(){renderDashboard();renderDepartments();renderEmployees();renderAttendance();renderLeaves();renderPayroll();renderPerformance();renderReports();renderNotifications();updateBadges()}
function renderDashboard(){const total=state.employees.length,present=state.attendance.filter(a=>a.date===today()&&a.status!=='Absent').length,leave=state.employees.filter(e=>e.status==='On Leave').length,pending=state.leaves.filter(l=>l.status==='Pending').length,gross=state.employees.reduce((s,e)=>s+e.salary/12,0);document.getElementById('sEmployees').textContent=total;document.getElementById('sPresent').textContent=present;document.getElementById('sPresentRate').textContent=(total?Math.round(present/total*100):0)+'% attendance rate';document.getElementById('sLeave').textContent=leave;document.getElementById('sPending').textContent=pending+' pending requests';document.getElementById('sPayroll').textContent=money(gross);document.getElementById('deptBars').innerHTML=state.departments.map(d=>{const n=state.employees.filter(e=>e.dept===d.name).length,p=Math.round(n/Math.max(total,1)*100);return `<div><div class="bar-label"><b>${esc(d.name)}</b><span>${n}</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join('');document.getElementById('activity').innerHTML=(state.activities.length?state.activities:[{text:'System ready',time:new Date().toLocaleString()}]).slice(0,6).map(a=>`<div class="report-row"><span>${esc(a.text)}</span><small>${esc(a.time)}</small></div>`).join('')}
function renderEmployees(){const q=(document.getElementById('empSearch').value||'').toLowerCase(),d=document.getElementById('empDept').value,s=document.getElementById('empStatus').value;document.getElementById('empDept').innerHTML='<option value="">All departments</option>'+state.departments.map(x=>`<option ${d===x.name?'selected':''}>${esc(x.name)}</option>`).join('');const data=state.employees.filter(e=>(!q||Object.values(e).some(v=>String(v).toLowerCase().includes(q)))&&(!d||e.dept===d)&&(!s||e.status===s));document.getElementById('employeeGrid').innerHTML=data.map(e=>`<article class="employee-card"><div class="emp-top"><span class="emp-avatar">${initials(e.name)}</span><span class="badge ${e.status==='Active'?'active':e.status==='On Leave'?'leave':'inactive'}">${e.status}</span></div><h3>${esc(e.name)}</h3><p class="muted">${esc(e.designation)}</p><div class="meta"><span>▤ ${esc(e.dept)}</span><span>✉ ${esc(e.email)}</span><span>☎ ${esc(e.phone)}</span><span>Joined ${esc(e.joined)}</span><b>${money(e.salary)}/month</b></div>${roleAllowed({dataset:{roles:'Admin,HR Manager'}})?`<div class="actions"><button class="secondary" onclick="employeeModal('${e.id}')">Edit</button><button class="danger" onclick="deleteEmployee('${e.id}')">Delete</button></div>`:''}</article>`).join('')||'<div class="card"><h3>No employees found</h3><p>Try another search or filter.</p></div>'}
function employeeModal(id){const e=state.employees.find(x=>x.id===id);openModal(id?'Edit employee':'Add employee',`<div class="two"><label>Full name<input name="name" required value="${esc(e?.name||'')}"></label><label>Employee ID<input name="id" required value="${esc(e?.id||'EMP'+(101+state.employees.length))}" ${id?'readonly':''}></label></div><div class="two"><label>Email<input name="email" type="email" required value="${esc(e?.email||'')}"></label><label>Phone<input name="phone" required value="${esc(e?.phone||'')}"></label></div><div class="two"><label>Department<select name="dept">${state.departments.map(d=>`<option ${e?.dept===d.name?'selected':''}>${esc(d.name)}</option>`).join('')}</select></label><label>Designation<input name="designation" required value="${esc(e?.designation||'')}"></label></div><div class="two"><label>Date joined<input name="joined" type="date" required value="${esc(e?.joined||today())}"></label><label>Monthly salary (KSh)<input name="salary" type="number" min="0" required value="${e?.salary||''}"></label></div><label>Status<select name="status">${['Active','On Leave','Inactive'].map(x=>`<option ${e?.status===x?'selected':''}>${x}</option>`).join('')}</select></label><button class="primary" type="submit">Save employee</button>`,form=>{const x=Object.fromEntries(new FormData(form));x.salary=Number(x.salary);if(id){Object.assign(e,x);log(`Updated employee ${x.name}`)}else{state.employees.push(x);log(`Added employee ${x.name}`)}save();closeModal();renderAll()})}
function deleteEmployee(id){const e=state.employees.find(x=>x.id===id);if(!confirm(`Delete ${e?.name}?`))return;state.employees=state.employees.filter(x=>x.id!==id);log(`Deleted employee ${id}`);save();renderAll();toast('Employee deleted')}
function renderDepartments(){document.getElementById('departmentTable').innerHTML=state.departments.map(d=>`<tr><td><b>${esc(d.name)}</b></td><td>${esc(d.manager)}</td><td>${state.employees.filter(e=>e.dept===d.name).length}</td><td>${money(d.budget)}</td><td>${user.role==='Admin'?`<button class="danger" onclick="deleteDepartment('${d.id}')">Delete</button>`:''}</td></tr>`).join('')}
function departmentModal(){openModal('New department',`<label>Department name<input name="name" required></label><label>Manager<input name="manager" required></label><label>Annual budget (KSh)<input name="budget" type="number" min="0" required></label><button class="primary" type="submit">Create department</button>`,form=>{const x=Object.fromEntries(new FormData(form));x.id='DEP'+Date.now();x.budget=Number(x.budget);state.departments.push(x);log(`Created department ${x.name}`);save();closeModal();renderAll()})}
function deleteDepartment(id){const d=state.departments.find(x=>x.id===id);if(state.employees.some(e=>e.dept===d.name))return toast('Move employees before deleting this department','error');if(!confirm('Delete '+d.name+'?'))return;state.departments=state.departments.filter(x=>x.id!==id);log(`Deleted department ${d.name}`);save();renderAll()}
function updateClock(){const n=new Date();document.getElementById('clockTime').textContent=n.toLocaleTimeString();document.getElementById('dateNow').textContent=n.toLocaleDateString(undefined,{weekday:'long',year:'numeric',month:'long',day:'numeric'});const a=state.attendance.find(x=>x.date===today()&&x.emp===user?.name);const active=a&&!a.checkOut;document.getElementById('clockStatus').textContent=active?`Clocked in at ${a.checkIn}`:'You are currently clocked out.';document.getElementById('clockBtn').textContent=active?'Clock out':'Clock in';document.getElementById('clockBtn').className=active?'danger':'success'}
function clock(){const idx=state.attendance.findIndex(x=>x.date===today()&&x.emp===user.name);if(idx<0){state.attendance.push({id:Date.now(),date:today(),emp:user.name,checkIn:new Date().toLocaleTimeString(),checkOut:'',hours:0,status:'On Time'});log(`${user.name} clocked in`)}else if(!state.attendance[idx].checkOut){const a=state.attendance[idx];a.checkOut=new Date().toLocaleTimeString();a.hours=8;a.status='Present';log(`${user.name} clocked out`)}save();renderAll()}
function renderAttendance(){document.getElementById('attendanceTable').innerHTML=state.attendance.slice().sort((a,b)=>b.date.localeCompare(a.date)).map(a=>`<tr><td>${a.date}</td><td>${esc(a.emp)}</td><td>${esc(a.checkIn)}</td><td>${esc(a.checkOut||'—')}</td><td>${a.hours||'—'}</td><td><span class="badge approved">${esc(a.status)}</span></td></tr>`).join('')||'<tr><td colspan="6">No attendance records yet.</td></tr>';updateClock()}
function leaveModal(){openModal('Apply for leave',`<label>Employee<select name="emp">${state.employees.map(e=>`<option>${esc(e.name)}</option>`).join('')}</select></label><div class="two"><label>Leave type<select name="type"><option>Casual Leave</option><option>Sick Leave</option><option>Paid Leave</option><option>Unpaid Leave</option></select></label><label>Reason<input name="reason" required></label></div><div class="two"><label>Start date<input name="start" type="date" required></label><label>End date<input name="end" type="date" required></label></div><button class="primary" type="submit">Submit request</button>`,form=>{const x=Object.fromEntries(new FormData(form));const days=Math.max(1,Math.round((new Date(x.end)-new Date(x.start))/864e5)+1);if(x.end<x.start)return toast('End date must be after start date','error');state.leaves.unshift({...x,id:'L'+Date.now(),days,status:'Pending'});log(`${x.emp} submitted a ${x.type} request`);save();closeModal();renderAll()})}
function renderLeaves(){document.getElementById('leaveTable').innerHTML=state.leaves.map(l=>`<tr><td>${esc(l.emp)}</td><td>${esc(l.type)}</td><td>${l.start} → ${l.end}</td><td>${l.days}</td><td>${esc(l.reason)}</td><td><span class="badge ${l.status.toLowerCase()}">${l.status}</span></td><td>${(user.role==='Admin'||user.role==='HR Manager')&&l.status==='Pending'?`<button class="success" onclick="decideLeave('${l.id}','Approved')">Approve</button> <button class="danger" onclick="decideLeave('${l.id}','Rejected')">Reject</button>`:'—'}</td></tr>`).join('');document.getElementById('balances').innerHTML=['Casual Leave','Sick Leave','Paid Leave'].map(t=>`<div class="balance"><span>${t}</span><strong>${t==='Casual Leave'?12:t==='Sick Leave'?10:20} days</strong><div class="bar"><i style="width:75%"></i></div></div>`).join('')}
function decideLeave(id,status){const l=state.leaves.find(x=>x.id===id);l.status=status;const e=state.employees.find(x=>x.name===l.emp);if(e)e.status=status==='Approved'?'On Leave':'Active';log(`Leave request for ${l.emp} was ${status.toLowerCase()}`);save();renderAll();toast('Leave '+status.toLowerCase())}
function payrollData(){return state.employees.map(e=>{const basic=e.salary,allow=Math.round(basic*.08),ded=Math.round(basic*.12),net=basic+allow-ded;return {...e,allow,ded,net}})}
function renderPayroll(){const rows=payrollData(),gross=rows.reduce((s,x)=>s+x.salary,0),all=rows.reduce((s,x)=>s+x.allow,0),ded=rows.reduce((s,x)=>s+x.ded,0),net=gross+all-ded;['grossPayroll','allowances','deductions','netPayroll'].forEach((id,i)=>document.getElementById(id).textContent=money([gross,all,ded,net][i]));document.getElementById('payrollTable').innerHTML=rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.salary)}</td><td>${money(x.allow)}</td><td>${money(x.ded)}</td><td><b>${money(x.net)}</b></td><td><span class="badge ${state.payroll[x.id]?'approved':'pending'}">${state.payroll[x.id]?'Processed':'Draft'}</span></td><td><button class="secondary" onclick="payslip('${x.id}')">Payslip</button></td></tr>`).join('')}
function processPayroll(){state.employees.forEach(e=>state.payroll[e.id]={month:new Date().toISOString().slice(0,7),processedAt:new Date().toLocaleString()});log('Monthly payroll processed successfully');save();renderAll();toast('Payroll processed')}
function payslip(id){const x=payrollData().find(e=>e.id===id),html=`<div style="padding:20px"><h1>EMS PAYSLIP</h1><p>${new Date().toLocaleString()}</p><hr><p><b>Employee:</b> ${esc(x.name)}</p><p><b>ID:</b> ${x.id}</p><p><b>Department:</b> ${esc(x.dept)}</p><p><b>Basic salary:</b> ${money(x.salary)}</p><p><b>Allowances:</b> ${money(x.allow)}</p><p><b>Deductions:</b> ${money(x.ded)}</p><h2>Net salary: ${money(x.net)}</h2></div>`;const w=window.open('','_blank');if(!w)return toast('Allow pop-ups to print the payslip','error');w.document.write('<html><body style="font-family:Arial">'+html+'</body></html>');w.document.close();w.print()}
function reviewModal(){openModal('New performance review',`<label>Employee<select name="emp">${state.employees.map(e=>`<option>${esc(e.name)}</option>`).join('')}</select></label><label>Rating<select name="rating"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select></label><label>Goal<input name="goal" required></label><label>Feedback><textarea name="feedback" rows="4" required></textarea></label><button class="primary" type="submit">Save review</button>`,form=>{const x=Object.fromEntries(new FormData(form));state.reviews.unshift({id:'R'+Date.now(),emp:x.emp,reviewer:user.name,rating:Number(x.rating),goal:x.goal,feedback:x.feedback});log(`Performance review created for ${x.emp}`);save();closeModal();renderAll()})}
function renderPerformance(){document.getElementById('performanceTable').innerHTML=state.reviews.map(r=>`<tr><td>${esc(r.emp)}</td><td>${esc(r.reviewer)}</td><td>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</td><td>${esc(r.goal)}</td><td>${esc(r.feedback)}</td><td></td></tr>`).join('')}
function renderReports(){const active=state.employees.filter(e=>e.status==='Active').length,leave=state.employees.filter(e=>e.status==='On Leave').length;document.getElementById('reportStats').innerHTML=[['Total employees',state.employees.length],['Active',active],['On leave',leave],['Departments',state.departments.length],['Pending leave',state.leaves.filter(x=>x.status==='Pending').length]].map(x=>`<div class="report-row"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');document.getElementById('payrollDept').innerHTML=state.departments.map(d=>{const n=state.employees.filter(e=>e.dept===d.name).reduce((s,e)=>s+e.salary,0);return `<div class="report-row"><b>${esc(d.name)}</b><span>${money(n)}/mo</span></div>`}).join('')}
function renderNotifications(){const unread=state.notifications.filter(n=>!n.read).length;document.getElementById('notifications').innerHTML=state.notifications.slice(0,40).map(n=>`<div class="notice ${n.read?'':'unread'}"><div><b>${esc(n.text)}</b><small>${esc(n.time)}</small></div></div>`).join('')||'<div class="card">No notifications.</div>';document.getElementById('notifBadge').textContent=unread;document.getElementById('topNotif').textContent=unread?'•':''}
function updateBadges(){document.getElementById('leaveBadge').textContent=state.leaves.filter(l=>l.status==='Pending').length}
function openModal(title,body,submit){document.getElementById('modalTitle').textContent=title;const f=document.getElementById('modalForm');f.innerHTML=body;f.onsubmit=e=>{e.preventDefault();submit(f)};document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden');document.getElementById('modalForm').innerHTML=''}
function exportCSV(name,rows){const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=name;a.click();URL.revokeObjectURL(a.href);toast('Export created')}
function payrollRows(){return [['Employee','ID','Department','Basic','Allowances','Deductions','Net'],...payrollData().map(x=>[x.name,x.id,x.dept,x.salary,x.allow,x.ded,x.net])]}
function attendanceRows(){return [['Date','Employee','Check in','Check out','Hours','Status'],...state.attendance.map(a=>[a.date,a.emp,a.checkIn,a.checkOut,a.hours,a.status])]}
function reportRows(){return [['Metric','Value'],['Employees',state.employees.length],['Active',state.employees.filter(e=>e.status==='Active').length],['On Leave',state.employees.filter(e=>e.status==='On Leave').length],['Departments',state.departments.length]]}
document.addEventListener('DOMContentLoaded',()=>{setup();start()});